# Numpy


In [245]:
# instalando numpy
# !pip install numpy
# cuando se instala un modulo o biblioteca, solo se hace una vez

In [31]:
!pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: C:\Users\NESTOR\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


## ejemplo básico

In [4]:
import numpy as np

In [32]:
# ejemplo1
arr = np.arange(15)
print(arr)
arr1 = np.clip(arr, 2, 10)
arr1

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([ 2,  2,  2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 10])

In [33]:
# ejemplo2
arr1 = np.zeros_like(arr)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# arr2 = np.clip(arr, 7, 37,out = arr1)
# arr2
np.clip(arr, 7, 37,out = arr1)

array([ 7,  7,  7,  7,  7,  7,  7,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
arr1

array([ 7,  7,  7,  7,  7,  7,  7,  7,  8,  9, 10, 11, 12, 13, 14])

## Matrices multidimensionales

In [34]:
import numpy as np

gradosCelcius = np.array([
   29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
   12.6, 49.9, 38.6, 31.3, 9.2, 22.2])
print(gradosCelcius.shape)
gradosCelcius

(12,)


array([29.3, 42.1, 18.8, 16.1, 38. , 12.5, 12.6, 49.9, 38.6, 31.3,  9.2,
       22.2])

In [35]:
# reshape => redimensiona el array
gradosCelcius = gradosCelcius.reshape(2, 2, 3)  # 2 capas, cada cada de 2 filas y 3 columnas
# 2 x 2 x 3 = 12
gradosCelcius

array([[[29.3, 42.1, 18.8],
        [16.1, 38. , 12.5]],

       [[12.6, 49.9, 38.6],
        [31.3,  9.2, 22.2]]])

In [36]:
# voy a intercambiar ejes
# shape = (2 , 2 , 3)
# ejes  =  0   1   2
np.swapaxes(gradosCelcius, 1, 2)

array([[[29.3, 16.1],
        [42.1, 38. ],
        [18.8, 12.5]],

       [[12.6, 31.3],
        [49.9,  9.2],
        [38.6, 22.2]]])

In [270]:
# otro ejemplo
tabla = np.array([
        [5, 3, 7, 1],
        [2, 6, 7 ,9],
        [1, 1, 1, 1],
        [4, 3, 2, 0],
    ])

tabla

array([[5, 3, 7, 1],
       [2, 6, 7, 9],
       [1, 1, 1, 1],
       [4, 3, 2, 0]])

In [271]:
tabla.shape

(4, 4)

In [37]:
tabla.max()

99999

In [273]:
tabla.max(axis=0)  # eje = 0 hace referencia al eje vertical

array([5, 6, 7, 9])

In [274]:
tabla.max(axis=1) # eje = 0 hace referencia al eje horizontal

array([7, 9, 1, 4])

In [275]:
# otro ejuemplo
A = np.arange(32).reshape(4, 1, 8)  # 4x1x8 =32
A

array([[[ 0,  1,  2,  3,  4,  5,  6,  7]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20, 21, 22, 23]],

       [[24, 25, 26, 27, 28, 29, 30, 31]]])

In [276]:
A.shape

(4, 1, 8)

In [277]:
B = np.arange(48).reshape(1, 6, 8)
B

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]]])

In [278]:
B.shape

(1, 6, 8)

In [280]:
# bradcasting
C = A + B
C

array([[[ 0,  2,  4,  6,  8, 10, 12, 14],
        [ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54]],

       [[ 8, 10, 12, 14, 16, 18, 20, 22],
        [16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62]],

       [[16, 18, 20, 22, 24, 26, 28, 30],
        [24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70]],

       [[24, 26, 28, 30, 32, 34, 36, 38],
        [32, 34, 36, 38, 40, 42, 44, 46],
        [40, 42, 44, 46, 48, 50, 52, 54],
        [48, 50, 52, 54, 56, 58, 60, 62],
        [56, 58, 60, 62, 64, 66, 68, 70],
        [64, 66, 68, 70, 72,

In [281]:
print("A=",A.shape)
print("B=",B.shape)
print("C=",C.shape)

A= (4, 1, 8)
B= (1, 6, 8)
C= (4, 6, 8)


## Operaciones para ciencia de datos

In [38]:
from math import e, factorial

In [39]:
e

2.718281828459045

In [40]:
factorial(4)

24

In [44]:
import numpy as np

fac = np.vectorize(factorial)
# factorial es una funcion con un solo argumento
# fac se convierta en una funcion que reciba un vector y calcula el factorial
# de cada componente del vector
fac(5)

array(120)

In [46]:
fac([1,2])

array([1, 2])

In [48]:
fac([3,5,7])

array([   6,  120, 5040])

## Detalles finales

* En general, las matrices de NumPy son más rápidas que las listas de Python.
* Sin embargo, dado que sólo es posible almacenar datos del mismo tipo en cada columna, las listas de Python son más flexibles.

In [24]:
from numpy import arange
from timeit import Timer

Nombre_elementos = 100000
Nombre_iteracion = 1000

tabla = arange(Nombre_elementos)
lista = range(Nombre_elementos)

In [25]:
tabla

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [26]:
lista

range(0, 100000)

In [27]:
time_numpy = Timer("tabla.sum()", "from __main__ import tabla")
time_list = Timer("sum(lista)", "from __main__ import lista")
print("tiempo medio en numpy en segundos: %.3e" % (time_numpy.timeit(Nombre_iteracion)/Nombre_iteracion,))
print("tiempo medio en listas en segundos:  %.3e" % (time_list.timeit(Nombre_iteracion)/Nombre_iteracion,))

tiempo medio en numpy en segundos: 1.463e-05
tiempo medio en listas en segundos:  9.412e-04


In [28]:
1.463e-05 > 9.412e-04

False

In [29]:
%%time
tabla.sum()

CPU times: total: 0 ns
Wall time: 0 ns


704982704

In [30]:
%%time
sum(lista)

CPU times: total: 0 ns
Wall time: 1 ms


4999950000